[package]
name = "lieutenant"
version = "0.1.0"
authors = ["Endominus <endominus@gmail.com>"]

[lib]
name = "lieutenant"
path = "src/lib.rs"

[dependencies]
json = "0.11.14"
reqwest = "*"
serde_derive = "*"
serde = "*"

[dependencies.rusqlite]
version = "0.20.0"
features = ["bundled"]
# ureq = { version = "*", features = ["json", "charset"] }

[dependencies.cursive]
version = "0.13"
default-features = false
features = ["crossterm-backend"]
