[package]
name = "lieutenant"
version = "0.1.0"
authors = ["Endominus <endominus@gmail.com>"]

[dependencies]
json = "0.11.14"
# reqwest = "0.8.8"
ureq = { version = "*", features = ["json", "charset"] }

[dependencies.cursive]
version = "0.11.2"
default-features = false
features = ["crossterm-backend"]
