[global]
tags = [
    "main", 
    "draw", 
    "board_wipe", 
    "removal",
    "ramp"
]
ordering = "-name"
default_filter = "text"

[decks]

    [decks.1]
    tags = ["recursion"]
    ordering = "+cmc"
    default_filter = "name"

    [decks.2]
    ordering = "-cmc"
