word = { negation? ~ (ASCII_ALPHANUMERIC | "_" | "{" | "}" )+ }
special_chars = { "\\" | "/" | "+" | " " | ":" | "-" | "." | "," | "\'" | "û" | "_" | "{" | "}" }
word_extended = { (ASCII_ALPHANUMERIC | special_chars)+ }
phrase = { negation? ~ "\"" ~ (word_extended) ~ "\"" }
number_range = { NUMBER ~ ("-" | "..") ~ NUMBER | (">" | "<") ~ NUMBER | NUMBER | "*" | "x" | "X" }
and_separator = { "+" | "&" }
or_separator = { "|" | "/" }
separator = { and_separator | or_separator }
negation = { "!" }
rarity_val = { negation? ~ ("c" | "u" | "r" | "m") }
color_val = { negation? ~ ("w" | "u" | "b" | "r" | "g" | "c") }

text_token = { (phrase | word) ~ (separator ~ text_token)* }
bracketed_text = { "(" ~ text_token ~ ")" }
color_token = { color_val ~ color_token* }

name = { ("name" | "na") ~ ":" ~ (bracketed_text | text_token) ~ (separator ~ (bracketed_text | text_token))* }
text = { ("text" | "te") ~ ":" ~ (bracketed_text | text_token) ~ (separator ~ (bracketed_text | text_token))* }
ctyp = { ("type" | "ty") ~ ":" ~ (bracketed_text | text_token) ~ (separator ~ (bracketed_text | text_token))* }
tag = { "tag:" ~ (bracketed_text | text_token | negation) ~ (separator ~ (bracketed_text | text_token | negation))* }
cmc = { "cmc:" ~ number_range }
power = { ("power" | "po" | "p") ~ ":" ~ number_range }
toughness = { ("toughness" | "tough" | "to") ~ ":" ~ number_range }
color = { ("color" | "c") ~ ":" ~ color_token ~ (or_separator ~ color_token)* }
identity = { "ci:" ~ color_token ~ (or_separator ~ color_token)* }
rarity = { ("rarity" | "r") ~ ":" ~ rarity_val+ }
sort = { "sort:" ~ ("+" | "-") ~ ("cmc" | "name") }

input = { (name | text | ctyp | tag | cmc | power | toughness | color | identity | rarity | sort | " ")+ }
