[global]
version = 1.0
tags = [
    "main", 
    "draw", 
    "board_wipe", 
    "removal",
    "ramp",
    "side",
]
ordering = "-name"
default_filter = "text"
recent = -1
open_into_recent = false

[decks]

    [decks.1]
    tags = [
        "bounce",
        "bypass",
        "cdt",
        "counter",
        "delay",
        "etb",
        "protection",
        "spy",
    ]
    ordering = "+cmc"
    default_filter = "name"

    [decks.3]
    ordering = "-cmc"
