[global]
version = 1.0
tags = [
    "main", 
    "board_wipe", 
    "draw", 
    "ramp",
    "removal",
    "side",
]
ordering = "+name"
default_filter = "name"
recent = -1
open_into_recent = false

[decks]